
services:
  app:
    build:
      context: C:\Users\Manikandan\IdeaProjects\HotelBookingApp
      dockerfile: Dockerfile
    container_name: hotelbooking_app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hotelbookingapp
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: hotelbooking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hotelbookingapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
