version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_booking_app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hotelBookingApp
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: hotel_booking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hotelBookingApp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  db_data:
